### ISSUE TITLE
Black screen when update

### ISSUE THREAD

**Issue by rosostolato** [solid-software/flutter_vlc_player#16] opened 2019-11-19 03:48 UTC
Whenever I update the app (like a hot reload, screen rotation, fullscreen mode, etc), the video turns to a black screen but the audio continues running... 

I tried to send the url again to create another instance of the video when I get the screen rotated, but I only get 2 playbacks running simultaneously with no video. I can even see the rotating animation rendering the first frame in the new square but then, it turns to a black screen again

**Comment by rosostolato** [comment] 2019-11-23 15:05
I tried the @NBTX pull request and now the bug is gone.

**Comment by solid-software** [comment] 2020-04-08 20:31
As 2.0.0 is released now with changes from @NBTX I'm closing this. Please reopen if it's still not working well.

**Closed by solid-software** 2020-04-08 20:31 UTC

**Comment by alr2413** [comment] 2020-07-31 10:41
Hi, 

It seems the issue is appeared again in the new version 3.

**Comment by jing-pei** [comment] 2021-04-05 21:09
No screen is displayed during hot reload

flutter_vlc_player: ^6.0.1 

flutter doctor -v

```shell
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.0.4 at /Users/angus/flutter
    • Framework revision b1395592de (4 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.0-rc4)
    • Android SDK at /Users/angus/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc4
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6015.53

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • M2007J22C (mobile) • qwq875q8z5em75hy • android-arm64  • Android 10 (API
      29)
    • macOS (desktop)    • macos            • darwin-x64     • macOS 11.2.3
      20D91 darwin-x64
    • Chrome (web)       • chrome           • web-javascript • Google Chrome
      89.0.4389.114
    ! Error: iPad is not connected. Xcode will continue when iPad is connected.
      (code -13)

• No issues found!
```

**Comment by mrvancor** [comment] 2021-11-12 11:43
Temporary solution:
```
    final isReadyToInitialize = _videoPlayerController.isReadyToInitialize ?? false;

    if (isReadyToInitialize) {
      final isPlaying = await _videoPlayerController.isPlaying() ?? false;

      if (isPlaying) {
        final position = await _videoPlayerController.getPosition();
        await _videoPlayerController.stop();
        await _videoPlayerController.play();
        await _videoPlayerController.seekTo(position);
      }
    }
```

For **RTSP** stream:
```
    final isReadyToInitialize = _videoPlayerController.isReadyToInitialize ?? false;

    if (isReadyToInitialize) {
      final isPlaying = await _videoPlayerController.isPlaying() ?? false;

      if (isPlaying) {
        await _videoPlayerController.stop();
        await _videoPlayerController.play();
      }
    }
```
