### ISSUE TITLE
RTMP is not working on IOS.

### ISSUE THREAD

**Issue by liqiang1995** [solid-software/flutter_vlc_player#178] opened 2021-02-10 19:05 UTC
How are you?
This package is great.
This package plays my RTMP on a test project (the test project has only VLC Player).
but RTMP is not played on my current project (it has too many other packages, firebase, google map, camera...).
I think a package suspends the VLC Player. or it is due to the memory limit of the iPhone.
I can not see any error log, so I can not know the package and reason.
Anyway, If you have any ideas, please let me know.
Thank you.

**Comment by liqiang1995** [comment] 2021-02-10 19:06
I am using the following packages.
  
  http: ^0.12.2
  html_unescape: ^1.0.2
  after_layout: ^1.0.7+2
  font_awesome_flutter: ^8.11.0
  path: ^1.7.0
  flutter_widget_from_html: ^0.5.1+5
  configurable_expansion_tile: 1.0.0
  timeago: ^2.0.29
  validate: 1.7.0
  country_pickers: ^1.3.0
  shared_preferences: ^0.5.12+4
  transparent_image: 1.0.0
  pull_to_refresh: ^1.6.3
  localstorage: 3.0.1+4
  page_indicator: 0.3.0
  extended_image: ^1.5.0
  intro_slider: ^2.3.3
  firebase_core: 0.4.5
  firebase_auth: 0.15.3 # with the latest firebase https://github.com/FirebaseExtended/flutterfire/issues/2084
  flutter_webview_plugin: ^0.3.11
  connectivity: ^2.0.2
  google_maps_flutter: 0.5.25+3
  place_picker: 0.9.11
  image_picker: ^0.6.7+12
  flutter_staggered_grid_view: 0.3.0
  auto_size_text: 2.1.0
  flutter_swiper: 1.1.6
  flutter_widgets: 0.1.12
  flutter_spinkit: 4.1.2+1
  percent_indicator: 2.1.1+1
  animated_text_kit: 2.0.0
  http_auth: 0.2.9
  pin_code_fields: 2.4.0
  flutter_facebook_login: 3.0.0
  rubber: 0.4.0
  flutter_localizations:
    sdk: flutter
  custom_splash: 0.0.2
  apple_sign_in: 0.1.0
  google_sign_in: 4.5.1
  google_fonts: 0.3.10
  app_settings: ^4.0.3
  animated_splash: 1.0.0
  country_code_picker: 1.3.7
  flutter_typeahead: 1.8.0
  flash: 1.2.3
  timezone:
  flutter_html:
  carousel_slider:
  toast: ^0.1.5
  stripe_payment: ^1.0.8
  flutter_device_locale:
  open_appstore: ^1.0.2
  dio: ^3.0.3
  shimmer: ^1.1.1
  progress_dialog: ^1.2.4
  multi_image_picker: ^4.7.10
  file_picker: ^1.12.0
  audioplayers: ^0.15.1
  dash_chat: ^1.0.9
  social_share_plugin: ^0.3.1+1
  fluwx: ^2.3.0
  flutter_youtube_view: ^1.1.9
  smooth_star_rating: ^1.1.1
  firebase_dynamic_links: 0.5.3
  flutter_barcode_scanner: ^1.0.1
  image_cropper: ^1.3.1
  video_trimmer: 0.2.7
  credit_card_slider: ^1.0.1
  card_scanner: ^0.2.0+3
  flutter_rtmp_publisher: ^0.0.1
  permission_handler: ^5.0.1+1
  sensors: ^0.4.2+6
  flutter_cube: ^0.0.3
  image: ^2.1.19
  adhara_socket_io: ^0.4.2+1
  pushy_flutter: ^1.1.2
  flutter_vlc_player: ^5.0.4
  pedantic: ^1.9.2
  device_apps: 1.0.9
  provider: ^4.3.2+2
  share: 0.6.3+6

**Comment by liqiang1995** [comment] 2021-02-11 01:19
I have found the package. it is due to video_trimmer: 0.2.7.
Do you have any idea to fix it?
Thank you

**Comment by mitchross** [comment] 2021-02-13 18:11
Does RTMP work in the example app?

**Comment by liqiang1995** [comment] 2021-02-13 18:11
yes
it is working now

**Comment by liqiang1995** [comment] 2021-02-13 18:13
video_trimmer: 0.2.7
If I use the video_trimmer, flutter_vlc_player does not play RTMP.

**Comment by liqiang1995** [comment] 2021-02-13 18:15
I think both video_trimmer and flutter_vlc_player use the FFmpeg package.

**Comment by mitchross** [comment] 2021-02-13 18:17
Can you please provide a sample app repo?

**Comment by liqiang1995** [comment] 2021-02-13 18:19
Please import the video_trimmer package to your sample app.
not need to do coding.
then flutter_vlc_player will not play RTMP in iOS.

**Comment by mitchross** [comment] 2021-02-13 19:07
Without a sample RTMP url, I cannot help. Please provide a sample RTMP url.

**Comment by liqiang1995** [comment] 2021-02-13 21:48
ok
http://live.yklmrealestate.com/live/test

**Comment by liqiang1995** [comment] 2021-02-13 21:51
![image](https://user-images.githubusercontent.com/54995513/107862586-99ceb300-6e88-11eb-9bbd-416cd6ff8a4f.png)

rtmp://live.yklmrealestate.com/live/test

**Comment by mitchross** [comment] 2021-02-13 22:07
Does not open in VLC Media Player. 
![Screen Shot 2021-02-13 at 5 06 29 PM](https://user-images.githubusercontent.com/6330506/107862852-e630d900-6e1d-11eb-9fe6-f75e7ee7b2f7.png)

**Comment by liqiang1995** [comment] 2021-02-13 22:08
You can upload a live-stream video yourself.

**Comment by mitchross** [comment] 2021-02-13 22:17
By Including "video_trimmer: 0.2.7" does it only break RTMP? I have included this package and all the videos play without issue.

This video URL "https://live.yklmrealestate.com/?key=test" does not play for me in the sample app. Please provide code so I can further debug.

**Comment by liqiang1995** [comment] 2021-02-13 22:26
if video_trimmer has included, App can play all videos except for RTMP.
1. open your sample project.
2. go to lib/single_tab.dart/41th line.
3 replace "http://samples.mplayerhq.hu/MPEG-4/embedded_subs/1Video_2Audio_2SUBs_timed_text_streams_.mp4" with "rtmp://live.yklmrealestate.com/live/test".
5. run the sample project.

**Comment by mitchross** [comment] 2021-02-13 22:40
It does not matter if "video_trimmer" is added or not, I cannot play the URL provided, nor can the desktop app play the URL.

![Screen Shot 2021-02-13 at 5 40 26 PM](https://user-images.githubusercontent.com/6330506/107863463-9a346300-6e22-11eb-8847-3d03dd0c2aa4.png)

**Comment by liqiang1995** [comment] 2021-02-13 22:48
Do you have OBS? then you need to upload a live-stream-video.

**Comment by liqiang1995** [comment] 2021-02-13 22:50
My skype id is "live:.cid.1af6cf74b98bcffa".

**Comment by mitchross** [comment] 2021-02-14 21:27
Ok @liqiang1995 I have finally reproduced this and can confirm your theory about "video_trimmer" causing the issue with RTMP. 

I ran logs with and without the video trimmer library. 

At the core the issue is that with the video trimmer library I see these logs

>  trying url: rtmp://192.168.1.9:1935/live/shed
> 2021-02-14 16:05:43.711024-0500 Runner[14729:3969728] [ERR] option quiet does not exist
> 2021-02-14 16:05:43.711069-0500 Runner[14729:3969728] [DBG] CPU flags: 0x00000068
> 2021-02-14 16:05:43.712555-0500 Runner[14729:3969728] [DBG] couldn't guess format

Without the video trimmer library I see

> trying url: rtmp://192.168.1.9:1935/live/shed
> 2021-02-14 16:15:53.549763-0500 Runner[14757:3974153] [ERR] option quiet does not exist
> 2021-02-14 16:15:53.549858-0500 Runner[14757:3974153] [DBG] CPU flags: 0x00000068
> 2021-02-14 16:15:53.550691-0500 Runner[14757:3974153] [DBG] detected format: flv


The video trimmer library uses flutter_ffmpeg, which is conflicting with vlc's embedded ffmpeg. I found this issue which perfectly matches up with the issue seen in the logs. https://github.com/tanersener/flutter-ffmpeg/issues/255 

The provided solution here is what you should try https://github.com/tanersener/mobile-ffmpeg/wiki/Using-Multiple-FFmpeg-Implementations-In-The-Same-iOS-Application.

Hope this helps.

**Comment by liqiang1995** [comment] 2021-02-14 23:35
Let me try.
Thank you.

**Comment by liqiang1995** [comment] 2021-02-15 15:59
How are you doing?
I have tried 2 solutions in the article you gave me.
but both are failed.
Are the solutions working for you?
thank you.

**Comment by mitchross** [comment] 2021-02-16 15:27
This issue is out of scope for this library. I'm not entirely sure how to resolve the issue. I guess you could try the solutions in the article directly on this library project? You could pull this repo and try.

**Comment by lan2000** [comment] 2021-04-14 08:41
> OK, thank you for your support.

Hello, is this problem solved?

**Closed** 2021-04-15 22:17 UTC
