### ISSUE TITLE
!!!Fatal Bug!!!: app crashes immediately as in the release mode

### ISSUE THREAD

**Issue by wmhseir3** [solid-software/flutter_vlc_player#251] opened 2021-08-18 00:09 UTC
The debug version of my app and the flutter_vlc_player example are both working smoothly.
However, both release mode apps are not. 
Spent hours to dig into this "crashes in release mode" issue as with my app with no clue.
And switch to the flutter_vlc_player example and found the same issue. 
Here are the steps to reproduce:
1.flutter_vlc_player-master\flutter_vlc_player\example>flutter run --release
2.the app just exit immediately as soon as the vlcplayer shows up in my android mobile screen.
3.the flutter doctor info are as followings:

[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1110], locale zh-TW)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Platform android-30, build-tools 30.0.0-rc1
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (3 available)

**Comment by alr2413** [comment] 2021-08-18 18:09
duplicate of #242.

**Closed** 2021-08-18 23:38 UTC
